//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseTemplate.Static.Templates.PurchaseTemplate.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class productDetails_aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal productDetails_aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PurchaseTemplate.Static.Templates.PurchaseTemplate.App_LocalResources.productDeta" +
                            "ils.aspx", typeof(productDetails_aspx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Cart.
        /// </summary>
        public static string addToCartLabel_InnerHtml {
            get {
                return ResourceManager.GetString("addToCartLabel.InnerHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string cartLabel_InnerHtml {
            get {
                return ResourceManager.GetString("cartLabel.InnerHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string checkoutLabel_InnerHtml {
            get {
                return ResourceManager.GetString("checkoutLabel.InnerHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Shopping.
        /// </summary>
        public static string continueShoppingLabel_InnerHtml {
            get {
                return ResourceManager.GetString("continueShoppingLabel.InnerHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string invalidMail_InnerHtml {
            get {
                return ResourceManager.GetString("invalidMail.InnerHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string moreLabel_InnerHtml {
            get {
                return ResourceManager.GetString("moreLabel.InnerHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string quantityLabel_InnerHtml {
            get {
                return ResourceManager.GetString("quantityLabel.InnerHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient Email.
        /// </summary>
        public static string recipientEmail_Placeholder {
            get {
                return ResourceManager.GetString("recipientEmail.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a recipient email address..
        /// </summary>
        public static string recipientEmailError_InnerHtml {
            get {
                return ResourceManager.GetString("recipientEmailError.InnerHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient Name.
        /// </summary>
        public static string recipientName_Placeholder {
            get {
                return ResourceManager.GetString("recipientName.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a recipient name.
        /// </summary>
        public static string recipientNameError_InnerHtml {
            get {
                return ResourceManager.GetString("recipientNameError.InnerHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send the card on a future date..
        /// </summary>
        public static string sendEcardDateLabel_InnerHtml {
            get {
                return ResourceManager.GetString("sendEcardDateLabel.InnerHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Email.
        /// </summary>
        public static string senderEmail_Placeholder {
            get {
                return ResourceManager.GetString("senderEmail.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a sender email address.
        /// </summary>
        public static string senderEmailError_InnerHtml {
            get {
                return ResourceManager.GetString("senderEmailError.InnerHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Name.
        /// </summary>
        public static string senderName_PlaceHolder {
            get {
                return ResourceManager.GetString("senderName.PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a sender name.
        /// </summary>
        public static string senderNameError_InnerHtml {
            get {
                return ResourceManager.GetString("senderNameError.InnerHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold Out.
        /// </summary>
        public static string watermark_InnerHtml {
            get {
                return ResourceManager.GetString("watermark.InnerHtml", resourceCulture);
            }
        }
    }
}
